vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /assets/images/users
            upload_destination: '%kernel.project_dir%/public/assets/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
